### ISSUE TITLE
Errors with sympy 1.7

### ISSUE THREAD

**Issue by mje-nz** [mph-/lcapy#41]
With sympy 1.7, a lot of the tests fail with errors like this:

```
Traceback (most recent call last):
  File "/home/runner/work/lcapy/lcapy/lcapy/tests/test_twoport.py", line 335, in test_transforms
    self.assertEqual(A.Gparams.Aparams.simplify(), A, "A.Gparams.Aparams")
  File "/home/runner/work/lcapy/lcapy/lcapy/twoport.py", line 491, in Gparams
    return GMatrix(self.Hparams.inv())
  File "/home/runner/work/lcapy/lcapy/lcapy/matrix.py", line 86, in inv
    Minv = matrix_inverse(sym.Matrix(self), method=method)
  File "/home/runner/work/lcapy/lcapy/lcapy/matrix.py", line 188, in matrix_inverse
    return dM.inv(method=method[3:]).to_Matrix()
TypeError: inv() got an unexpected keyword argument 'method'
```

**Comment by mph-** [comment]
Ah, this is experimental in SymPy.  Thanks for letting me know.  I've pushed a fix.
